version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/default-nginx-site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3320:80
    links:
      - clamav_rest:clamav_rest
  clamav_rest:
    build: .
    volumes:
      - ./:/srv/clamav-rest
    links:
      - clamd:clamd
    environment:
      - APP_CONFIG=config.TestConfig
  clamd:
    image: gcr.io/sre-docker-registry/github.com/uktrade/docker-clamav:master
    ports:
      - 3310:3310
    environment:
      - MIRROR_URL=db.local.clamav.net
      
