name: Intégration continue 

on:
  wokflow_dispatch: 
  push:
    branches: [main]
  release:
    types: [published]
  
defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Tests unitaires
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.9,3.10,3.11]
    services:
      clamav:
        image: gcr.io/sre-docker-registry/github.com/uktrade/docker-clamav:master
        env:
          MIRROR_URL: db.local.clamav.net
      
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install Dependencies
        run: |
          pip install -r ./requirements.txt

      - name: Run ClamAV

      - name: Wait up to 120 seconds for clamav container to start
        run: |
          for i in `seq 1 120`;
          do
            nc -z localhost 3310 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo clamav container never arrived && exit 1

      - name: Wait for clamav to be ready
        run: |
          for i in `seq 1 20`;
          do
              result=$(echo "PING" | nc 127.0.0.1 3310)
              
              if [ "$result" == "PONG" ]; then
                  echo $result
                  exit 0
              fi
              
              echo -n .
              sleep 1
          done
          echo Failed waiting for clamav && exit 1

      - name: Run unit tests
        run: |
          APP_CONFIG=config.CiConfig python -m unittest tests.py -f
